version: '3.4'

services:
  dotnet.factory.generic.datalayer.webapi:
    image: ${DOCKER_REGISTRY-}dotnetfactorygenericdatalayerwebapi
    build:
      context: .
      dockerfile: test/DotNet.Factory.Generic.DataLayer.WebApi/Dockerfile

  sampledb:
    image: mcr.microsoft.com/mssql/server:2017-latest
